#Merging 2 dataframes

In [3]:
import numpy as np

import pandas as pd

In [4]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [5]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [6]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [29]:
pd.merge(employees,salaries) #this will give common rows and merge them

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

### In merging **how = "inner"** means that it will give only common rows

### In merging **how = "outer"** means that it will give all the rows with NaN

In [32]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [9]:
df1=pd.merge(employees,salaries,on="employee_id",how="outer")
df1

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [10]:
df1.fillna(value="Unknown")

   employee_id     name department   salary    bonus
0            1     John         HR  60000.0   5000.0
1            2     Anna         IT  80000.0  10000.0
2            3    Peter    Finance  65000.0   7000.0
3            4    Linda         IT  Unknown  Unknown
4            5      Bob         HR  Unknown  Unknown
5            6  Unknown    Unknown  70000.0   8000.0
6            7  Unknown    Unknown  90000.0  12000.0

##Concatenation of 2 dataframes

In [11]:
daf1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

daf2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [12]:
daf1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [13]:
pd.concat([daf1,daf2])  #this concates in columns wise

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [14]:
pd.concat([daf1,daf2],axis =1) #this concatnates rows wise

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

#Joining 2 dataframes

In [15]:
f1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
f2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [23]:
new_f1=f1.join(f2,how="outer")
new_f1.fillna(value=0)

      name  score
1    Alice    0.0
2      Bob   85.0
3  Charlie   90.0
4        0   75.0

In [27]:
f2.join(f1,how="outer")

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN