#Creating Dataframe

In [4]:
import numpy as np
import pandas as pd

In [5]:
employees = {
    "Name": ["Aarav", "Priya", "Rohan", "Sneha", "Arjun", "Meera"],
    "age": [24, 26, 23, 25, 27, 22],
    "city": ["Bangalore", "Mumbai", "Pune", "Hyderabad", "Chennai", "Delhi"],
    "salary": [55000, 62000, 48000, 58000, 70000, 45000]
}

In [6]:
df=pd.DataFrame(employees) ## multiple series becomes dataframe

In [7]:
df

    Name  age       city  salary
0  Aarav   24  Bangalore   55000
1  Priya   26     Mumbai   62000
2  Rohan   23       Pune   48000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000
5  Meera   22      Delhi   45000

In [8]:
employees = [     ##if there are no keys given then it will default have index in table
    ["Aarav", 24, "Bangalore", 55000],
    ["Priya", 26, "Mumbai", 62000],
    ["Rohan", 23, "Pune", 48000],
    ["Sneha", 25, "Hyderabad", 58000],
    ["Arjun", 27, "Chennai", 70000],
    ["Meera", 22, "Delhi", 45000]
]

df2= pd.DataFrame(employees)
df2

       0   1          2      3
0  Aarav  24  Bangalore  55000
1  Priya  26     Mumbai  62000
2  Rohan  23       Pune  48000
3  Sneha  25  Hyderabad  58000
4  Arjun  27    Chennai  70000
5  Meera  22      Delhi  45000

In [9]:
colm = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(employees,columns=colm) ## adding columns manually
df2

    Name  Age       City  Salary
0  Aarav   24  Bangalore   55000
1  Priya   26     Mumbai   62000
2  Rohan   23       Pune   48000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000
5  Meera   22      Delhi   45000

##Selection and indexing of columns

In [10]:
df2

    Name  Age       City  Salary
0  Aarav   24  Bangalore   55000
1  Priya   26     Mumbai   62000
2  Rohan   23       Pune   48000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000
5  Meera   22      Delhi   45000

In [11]:
df2["Name"] #accessing any column by entering the column name
            # Dataframe = ["Col name"]

0    Aarav
1    Priya
2    Rohan
3    Sneha
4    Arjun
5    Meera
Name: Name, dtype: object

In [12]:
df2["Age"]

0    24
1    26
2    23
3    25
4    27
5    22
Name: Age, dtype: int64

In [13]:
df2["City"]

0    Bangalore
1       Mumbai
2         Pune
3    Hyderabad
4      Chennai
5        Delhi
Name: City, dtype: object

In [14]:
##accessing two or more columns at once [["col 1","col 2" ]]
df2 [["Name","City"]]

    Name       City
0  Aarav  Bangalore
1  Priya     Mumbai
2  Rohan       Pune
3  Sneha  Hyderabad
4  Arjun    Chennai
5  Meera      Delhi

##Creating a new column

In [22]:
df2["Job Role"] = ["Doctor","Artist","singer",'dancer',"engineer","chef"]

In [23]:
df2

    Name  Age       City  Salary Designantion  Job Role
0  Aarav   24  Bangalore   55000       Doctor    Doctor
1  Priya   26     Mumbai   62000       Artist    Artist
2  Rohan   23       Pune   48000       singer    singer
3  Sneha   25  Hyderabad   58000       dancer    dancer
4  Arjun   27    Chennai   70000     engineer  engineer
5  Meera   22      Delhi   45000         chef      chef

##removing any column and row

##### only giving the name and axis wont delete the row or column from the main memeory it will just give a copy without that row or column,To delete it from main memory we have to use **[inplace=True**] then it will remove from the actual memory also.

In [41]:
df2.drop("Name",axis=1,inplace=True) #delete any column by their name

In [43]:
df2.drop(2,axis=0,inplace=True) #delete any row by indices

In [44]:
df2

   Age       City  Salary Designantion
3   25  Hyderabad   58000       dancer
4   27    Chennai   70000     engineer

In [45]:
df2

   Age       City  Salary Designantion
3   25  Hyderabad   58000       dancer
4   27    Chennai   70000     engineer

##Selecting Rows

In [50]:
df2.loc[[3]] #we use [loc] for selecting rows loc is location

   Age       City  Salary Designantion
3   25  Hyderabad   58000       dancer

##Selecting Subsets of Rows and columns

In [51]:
# we will make new dataframe3

Students = {
    "Name": ["Aarav", "Priya", "Rohan", "Sneha", "Arjun", "Meera"],
    "age": [24, 26, 23, 25, 27, 22],
    "city": ["Bangalore", "Mumbai", "Pune", "Hyderabad", "Chennai", "Delhi"],
    "salary": [55000, 62000, 48000, 58000, 70000, 45000]
}

In [54]:
df3=pd.DataFrame(Students)

In [55]:
df3

    Name  age       city  salary
0  Aarav   24  Bangalore   55000
1  Priya   26     Mumbai   62000
2  Rohan   23       Pune   48000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000
5  Meera   22      Delhi   45000

In [58]:
df3.loc[[0,1],["city","salary"]] # using loc and then give the rows you want and columns you want to access

        city  salary
0  Bangalore   55000
1     Mumbai   62000

In [60]:
df3.loc[[4,5],["Name","age"]]

    Name  age
4  Arjun   27
5  Meera   22

##Conditional Selection

In [61]:
df3

    Name  age       city  salary
0  Aarav   24  Bangalore   55000
1  Priya   26     Mumbai   62000
2  Rohan   23       Pune   48000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000
5  Meera   22      Delhi   45000

In [66]:
df3[df3["age"]>=25]

    Name  age       city  salary
1  Priya   26     Mumbai   62000
3  Sneha   25  Hyderabad   58000
4  Arjun   27    Chennai   70000

In [71]:
df3[(df3["age"]>=20) & (df3["city"]=="Pune")] # the format must be df3[(condition)&(condition)]

    Name  age  city  salary
2  Rohan   23  Pune   48000