#Pandas DataFrames Operations **(IMP)**

In [2]:
import numpy as np
import pandas as pd

In [4]:
df1 = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [10,20,30,40,50],
    'C': [100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [6]:
df1.shape   # shape is used to see the number of columns and rows

(5, 3)

In [8]:
df1.columns # columns is used to see what are the columns names

Index(['A', 'B', 'C'], dtype='object')

In [9]:
df1.info()  # info() gives the complete information of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [10]:
df1.describe() #describe() gives all the metrics of the table, like max min, count, percentage etc

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [13]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#DataFrames Applying Functions

In [15]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [16]:
def square(x):
  return x**2

In [32]:
df1['D']= df1["B"].apply(lambda x: x**2)

In [33]:
df1

   A   B    C    D
0  1   1  100    1
1  2   4  200   16
2  3   9  300   81
3  4  16  400  256
4  5  25  500  625

In [30]:
def addition(x):
  return x+x

In [31]:
df1["A"].apply(addition)

0     2
1     4
2     6
3     8
4    10
Name: A, dtype: int64