#Pandas Series

In [1]:
import numpy as np
import pandas as pd

In [8]:
labels = ["a","b","c"]
lists = [10,20,30,40,50,60]
arr = np.array([10,20,30])
di = {1:20,2:30,3:40}

In [18]:
pd.Series(di)

1    20
2    30
3    40
dtype: int64

In [17]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64