#Missing Data

In [1]:
import numpy as np
import pandas as pd

##Finding missing data

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, np.nan, np.nan, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}                   #np.nan means NOT A NUMBER

dataf=pd.DataFrame(data)
dataf

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  NaN  NaN
2  NaN  3.0  NaN  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [7]:
dataf.isna()

       A      B      C      D
0  False   True  False  False
1  False  False   True   True
2   True  False   True   True
3  False  False   True   True
4  False  False   True  False

In [11]:
dataf.isna().sum()

A    1
B    1
C    4
D    3
dtype: int64

In [10]:
dataf.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

##Removing the missing data

In [15]:
dataf.dropna() #all the rows got deleted since all the rows had null values

Empty DataFrame
Columns: [A, B, C, D]
Index: []

###threshold

In [23]:
dataf.dropna(thresh=3) # thresh counts non-missing values not missing values

     A    B    C    D
0  1.0  NaN  1.0  1.0
4  5.0  5.0  NaN  5.0

##filling the missing values

In [28]:
dataf.fillna(0) ## to fill the nan values we use (fillna)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  0.0  0.0
2  0.0  3.0  0.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [34]:
values ={"A":0,"B":2,"C":6,"D":8}  ##column wise filling
dataf.fillna(value=values)

     A    B    C    D
0  1.0  2.0  1.0  1.0
1  2.0  2.0  6.0  8.0
2  0.0  3.0  6.0  8.0
3  4.0  4.0  6.0  8.0
4  5.0  5.0  6.0  5.0